### ISSUE TITLE
Tart registry operations speed

### ISSUE THREAD

**Issue by victor-yousician** [cirruslabs/tart#234] opened 2022-09-07 07:05 UTC
Our setup: m1 mac mini in MacStadium datacenter in Dublin on a 1 Gb/s connection (speedtest confirms that that's what we have).
Image size - 77.8 GB, not using the chunksize parameter
AWS ECR (Ireland) - push and pull max out at 19 MB/s and take over an hour.
ghcr.io - push 10 MB/s, takes over 2 hours, pull 51 MB/s - 25 minutes
Is this normal? Any way to improve that?

**Comment by fkorotkov** [comment] 2022-09-09 17:14
That's weird. I was able to reproduce a low speed of around 19 MB/s (160 Mpbs) in a similar setup where I had a Mac Mini on a symmetric 1 Gbps channel in a datacenter North America and was pushing to GitHub's registry.

I usually push images from home where I have an asymmetric 1 Gbps channel (only have 40 MB/s uplink). And when I push from home I always max out the uplink. It weird to see that I see slower push from a datacenter.

Me and @edigaryev were discussing to get rid of the overly complex https://github.com/swift-server/async-http-client which seems introducing more complexity then benefits... Especially when things like #168 happens.

**Comment by edigaryev** [comment] 2022-09-09 17:28
@victor-yousician can you check the speed against a server running on `localhost`? This will allow us to establish some more-or less reproduce baseline and, perhaps, solve your issue.

Here's an instruction on how to do that: https://github.com/cirruslabs/tart/issues/165#issuecomment-1213211307.

**Comment by victor-yousician** [comment] 2022-09-29 08:52
I built and ran a docker registry locally (without a container) on a Mac Studio (M1U/20/64/32/128GB/4TB/10G). Tested with the same image - 77.8 GB.
Push 138 MB/s - 9:36
Pull 340 MB/s - 3:54
Registry version
./registry github.com/distribution/distribution/v3 v2.7.0-2021-g78b9c98c

**Comment by edigaryev** [comment] 2022-10-04 20:00
@victor-yousician could you check if the Tart build in the #260 (https://cirrus-ci.com/task/6068291209789440) improves things for you?

Note that this binary won't be able to start a VM, only do basic operations like listing VMs and pulling/pushing them.

**Comment by edigaryev** [comment] 2022-10-05 11:37
@victor-yousician actually the #260 was just released [as a part of Tart 0.30.0 version](htps://github.com/cirruslabs/tart/releases/tag/0.30.0), please check it out.

Will close this for now.

**Comment by victor-yousician** [comment] 2022-10-06 11:44
local pull speed improved nicely - 483 MB/s (up from 340 MB/s)
local push speed went down a little - 134 MB/s (down from 138 MB/s)
Something I noticed with the push in Activity Monitor - network speed is higher at the beginning of the push and MUCH lower at the end. I would expect the opposite, assuming that first we read the portion of the image file that has been modified and is not as easily compressible as the end of the image file that hasn't been touched and contains just zeros.

**Comment by edigaryev** [comment] 2022-10-14 14:48
> That's weird, but we see a dramatic step back in terms of registry pull speed with 0.30.0. Didn't measure the exact speed yet, but just noticed that on 0.30.0 the pull of an image (~170GB) took ~6 hours while pulling the same image with 0.29.0 takes about ~25 min. The registry is running within the same local network as the host. I used `--insecure` flag for the transfer if that matters.

Would be interesting to see the speed comparison, because in my local `--insecure` tests against `localhost` the speed remained the same.

You could also try out [the new 0.31.0](https://github.com/cirruslabs/tart/releases/tag/0.31.0) version, with has a memory leak fix that (https://github.com/cirruslabs/tart/pull/267) might influence the upload process speed.

**Comment by remarkov** [comment] 2022-10-14 15:35
The test environment where I am able to reproduce this: two M1 minis in the same network, both macOS 12.6. Host #1 has docker registry container running under colima all with default settings and a single ~170 GB image pushed into the registry. Host #2 has nothing but tart installed and pulling the image with `tart pull --insecure 10.0.0.2:5000/image-name image-name`
Doing this in tart 0.29.0 I'm getting the transfer speed of ~120 MB/s while with 0.30.0+ I'm getting only ~8 MB/s. As you can see, the difference is huge thus we had to rollback to 0.29.0 on the hosts where we already upgraded to `latest`.

**Comment by fkorotkov** [comment] 2022-10-14 20:11
@victor-yousician BTW is your host running Ventura or Monterey?

**Comment by fkorotkov** [comment] 2022-10-14 22:13
Yeah, I've verified on that there is a regression in speed on both Monterey and Ventura hosts. I'm quite puzzled by that. 😪

**Comment by victor-yousician** [comment] 2022-10-17 06:45
> @victor-yousician BTW is your host running Ventura or Monterey?

```
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```
I am pretty sure I retested with 0.30.0 and speeds were [fine](https://github.com/cirruslabs/tart/issues/234#issuecomment-1269879856) (compared to 8MB/s I'm getting now). But I've run some setup scripts on that box since then and I'm no longer sure if those screwed something up or I'm seeing the same regression.

**Comment by edigaryev** [comment] 2022-10-20 09:50
Closing because this was resolved by https://github.com/cirruslabs/tart/pull/282, but not automatically closed unlike the https://github.com/cirruslabs/tart/issues/279.

**Closed by edigaryev** 2022-10-20 09:50 UTC
Labels: bug
