### ISSUE TITLE
VMs do not get assigned IPs regularly

### ISSUE THREAD

**Issue by fmoc** [cirruslabs/tart#479] opened 2023-04-27 16:33 UTC
It seems to be a known problem that when cloning VMs, one may not get an IP address assigned. Therefore (and because I often need to make minor adjustments) I create almost all VMs using packer, which works well most of the time.

However, sometimes (and I cannot tell exactly when or why), the VMs do not get assigned an IP address. This cannot be detected unless the output of `tart ip ...` is string-matched against a known value. There is no way to fix this (although at first, rebooting seemed to help, it does not). The VM must be deleted and recreated, otherwise there is no chance of receiving an IP address.

As this is an intermittent problem, I cannot provide steps how to reliably reproduce this bug. I can tell from experience that bug rarely occurs on two hosts which run a single tart VM created by configuration management, and happens regularly on another host which hosts two VMs also created by configuration management (usually in sequence with little delay).

Please let me know what kind of information is useful to you to debug this problem.

**Comment by fkorotkov** [comment] 2023-04-27 17:36
Hey @fmoc, could you please provide some details of how the VMs are getting created? Do you do a lot of `clone/run/delete` loop for running some tests? If so, do you clone from a local VM or a remote VM that is cached?

**Comment by fmoc** [comment] 2023-04-28 10:48
That was causing it initially, yes. Now, I `tart delete` and `packer build` only on changes, maybe once a date, since the tart VMs are used as CI runners now. Packer clones a local VM.

**Comment by fkorotkov** [comment] 2023-04-28 15:46
When Tart clones a VM it checks that all local VMs have unique MAC addresses and generates a new one if needed. In your case Tart will always generate a new MAC address which might contribute to getting the flake. Ideally, for `clone/run/delete` loop we recommend to clone from a remote VM specifically to make sure everything is more stable. We follow this principle for Cirrus CI and Cirrus Runners where we have dozens and sometimes 100+ such loops every day without similar issues.

BTW I assumed that you have a macOS VM. For Linux VMs situation is slightly different and depends on the distribution.

**Comment by edigaryev** [comment] 2023-05-05 12:27
Do you create more than 253 new VMs per day?

If so, this might be a [DHCP exhaustion](https://github.com/cirruslabs/softnet#working-model) and can be solved by re-using MAC-addresses or using [Softnet](https://github.com/cirruslabs/softnet), which has a fix that decreases the DHCP lease time from 1 day to 10 minutes.

**Comment by fmoc** [comment] 2023-05-08 18:28
No, not at all, way less than that. But I also thought of something like that. I occasionally rebooted in an attempt to reset the IP address pool, with varying success... Does macOS create logs from its built-in DHCP server?

As long as I have the NAT workaround in place to fix compatibility with OpenVPN, I don't think I can easily use softnet...

**Comment by fkorotkov** [comment] 2023-05-08 23:32
I guess for such use case when a local VM is used for `clone/run/delete` loop we can add a flag to skip new MAC address validation. This will only work when host has one VM because if you'll run two VMs with the same MAC addresses you'll be in trouble. @edigaryev what do you think? I've created #493 as a possible option?

Will be great to find out the root cause but since we don't have visibility in the `Virtualizaion.Framework` internals.

**Comment by fmoc** [comment] 2023-05-09 09:46
@fkorotkov what's the big difference between cloning a local VM and an OCI one regarding IP/MAC address assignment?

Maybe distinguishing between image and VM locally, too, could help.

**Comment by fkorotkov** [comment] 2023-05-09 10:43
Let me first describe how Tart runs VMs and why MAC address generation is in place.

Tart can only run local VMs. When a local VM is started it gets an IP based on the MAC address. If you stop a VM and run it again, most likely it will have the same IP since the DHCP lease will be still presented.

But Tart can run up to two VMs at a time but you can't run two VMs with the same MAC address because it will screw networking for both of them. In #45 I introduced logic that upon cloning makes sure that all local VMs have unique MAC addresses so every two of them can run simultaneously without issues.

^^ this is why in @fmoc case every clone will get a new MAC address generate and therefore IP allocation. Even though the base VM is never run in parallel with the cloned ones.

Alternatively to #493 we can probably change logic and move the MAC conflict detection from `clone`/`import` to the actual `run`. Since #45 we now have file locks and we can detect that a VM is running. Therefore before `run` we can check that a VM that is about to start doesn't conflict with any running VM and regenerate a MAC address if needed. What do you think @edigaryev about essentially making the MAC conflict detection lazy?

**Comment by edigaryev** [comment] 2023-05-09 11:19
> Alternatively to #493 we can probably change logic and move the MAC conflict detection from `clone`/`import` to the actual `run`. Since #45 we now have file locks and we can detect that a VM is running. Therefore before `run` we can check that a VM that is about to start doesn't conflict with any running VM and regenerate a MAC address if needed. What do you think @edigaryev about essentially making the MAC conflict detection lazy?

I think it's a bit too magical. People will have a hard time estimating which of the VMs in a collision group would get its MAC-address changed first, which may be an important factor for those who use `--net-bridged` and add a static lease with VM's MAC-address to their local DHCP server.

What do you think about documenting this instead? We still don't know if @fmoc's case is due to the DHCP exhaustion, but if it's the case, and I'm assuming this is not a casual Tart usage, it can be worked around pretty easily by tuning the DHCP server's settings, which we can document in a few lines.

**Comment by fmoc** [comment] 2023-05-09 11:26
Why not give the user some way of rotating the VM's IP/MAC address on demand, maybe even as a flag for `tart run` (e.g., `tart run --rotate-mac` or even `tart run --require-ip` to make sure one is assigned)? In my case, I don't depend on a static IP address over the lifetime of the VM, but some people might need that.

By the way, I guess I wouldn't even mind this issue so much if it was easier to detect the problem. As said, often a reboot helps. Right now, we don't have logging in place. A `--run` won't log whether an IP was assigned, which I consider to be essential. A `tart run --detach --require-ip` kind of call, as suggested in #374, would improve the user experience significantly.

**Comment by fmoc** [comment] 2023-05-10 13:30
It happened again today while trying to build the containers. The third time I rebooted (after removing the offending VM first) I managed to recreate it with `packer`. I had lowered the lease times to 60 seconds.

**Comment by edigaryev** [comment] 2023-05-10 13:37
@fmoc so, this happens only on specific hosts? How often? Is it reproducible if you run the same steps on other hosts? If so, what would be the steps to reproduce this?

**Comment by fmoc** [comment] 2023-05-10 14:32
No, it happens on all of them, but is not clearly reproducible. That's the major issue. I'll keep updating this issue with all the information I have, but I don't have a lot of experience with macOS...

**Comment by fkorotkov** [comment] 2023-05-18 12:42
Hey @fmoc, how are doing with the issue? Have the workaround helped you?

**Comment by fmoc** [comment] 2023-06-01 10:33
I have not got around to moving my images on a registry. I'll post an update then.

**Comment by fkorotkov** [comment] 2023-07-08 16:34
Closing for now until we have more data.

**Closed by fkorotkov** 2023-07-08 16:34 UTC
Labels: question, needs-user-input
