### ISSUE TITLE
Tart MacOs Monterey default image can not make http request

### ISSUE THREAD

**Issue by emartynov** [cirruslabs/tart#255] opened 2022-09-22 21:12 UTC
Hi people,

Maybe I'm doing something stuipid. Just no experience at all.
All my wget requests in the console can resolve the ip for host but then they just stuck.
What can be the issue?

**Comment by fkorotkov** [comment] 2022-09-22 23:11
Can it be a duplicate of https://github.com/cirruslabs/tart/issues/72#issuecomment-1129170005? Could you please check if you have Internet Sharing enabled on the host? 🤔

**Comment by emartynov** [comment] 2022-09-23 07:19
So I have VPN and Firewall on my laptop. After disabling both of them - I got the network working.

Funny, when I enabled it back, it continued working. When I restarted tart, it stopped working again.

I'm playing on my laptop. So probably not the main application of the tart. Feel free to close it.

And knowing Apple, that might take ages to report and find the reason or fix.

**Comment by magnusviri** [comment] 2022-09-23 11:42
I don't think this is an Apple thing. When I used VMware on Intel Macs I had similar issues with VPN. Networking can just be difficult when doing VMs and firewalls. vSphere/ESXi has it's own virtual switches to deal with this.

**Comment by emartynov** [comment] 2022-09-23 12:34
Thanks! Closed for now.

**Closed** 2022-09-23 12:34 UTC
Labels: bug, question

**Comment by bldrvnlw** [comment] 2022-12-07 10:10
I had something similar - the packer build couldn't pull brew from github.com. Other URLs didn't work either. Turned out to be a DNS issue (ip ping was working).

More detail: - my macmini M1 is on a private subnet behind a windows desktop which was sharing its network connection. Perhaps that is not relevant but adding the address of this desktop/subnet master to the DNS list  made things work . Added this in the pkr.hsl:

```
networksetup -setdnsservers Ethernet 192.168.37.1 8.8.8.8 8.8.8.4
```

where 192.168.37.1 is the address of the subnet master.
