### ISSUE TITLE
Signing into iCloud

### ISSUE THREAD

**Issue by rahb3rt** [cirruslabs/tart#817] opened 2024-05-08 16:56 UTC
Hey guys, I was trying to figure out if there is a way to use iCloud sign in with this? its not letting me do that at all. I keep getting: Verification Failed. Error unknown. if anyone has any tips on this that would be great!

**Comment by edigaryev** [comment] 2024-05-08 16:58
Duplicate of https://github.com/cirruslabs/tart/issues/722.

**Closed by edigaryev** 2024-05-08 16:58 UTC
