### ISSUE TITLE
tart push very slow

### ISSUE THREAD

**Issue by hokadiri** [cirruslabs/tart#377] opened 2023-01-16 05:31 UTC
tart push is very slow for me. 
Testing to push `ventura-base ` to my registries.

private registry: pushing 1% took 25 mins. 
pushing to gcr: 1% took 11mins

```
$ tart --version
0.36.3
```
Running from an M1 Mac Pro. MacOS Ventura.

I've seen other reports about it (https://github.com/cirruslabs/tart/issues/279, https://github.com/cirruslabs/tart/issues/234, etc) but still have the issues. 

Is there a solution or workaround to it?

**Comment by fkorotkov** [comment] 2023-01-16 23:05
Could you please provide a little more information about your setup? 

- What kind of registry you are using? What's the version?
- What's the network situation between your location and the registry?
- Have you tried to push a docker container and what was the speed?
- Is there anything suspicious in Activity Monitor for the registry?

**Comment by hokadiri** [comment] 2023-01-17 02:05
> What kind of registry you are using?

docker registry. tested with both gcr.io & jfrog artifactory

> What's the version?

not sure

> What's the network situation between your location and the registry?

Pretty good. jfrog artifactory is in atlanta. gcr.io is [somewhere in the US](https://cloud.google.com/container-registry/docs/overview)
- Office network (Both Wifi & Ethernet)
-  VPN


> Have you tried to push a docker container and what was the speed?

Yes, pushed to gcr & jfrog artifactory. Both are significantly faster

> Is there anything suspicious in Activity Monitor for the registry?

Yes. 
Speedtest is pretty good. 800Mbps uploads. 
But activity monitor shows uploads in the kbps. Max i've seen is 3Mbps
<img width="536" alt="Screenshot 2023-01-16 at 6 02 15 PM" src="https://user-images.githubusercontent.com/678342/212793668-d84d8fbf-34d8-4cd0-96f3-7834f10e9bfc.png">
<img width="716" alt="Screenshot 2023-01-16 at 6 01 50 PM" src="https://user-images.githubusercontent.com/678342/212793681-8f2a80df-e9fb-402b-98ff-ea0f3297e064.png">

**Comment by hokadiri** [comment] 2023-01-17 15:13
Its faster (and bursty) but it hits 120MBps
<img width="761" alt="Screenshot 2023-01-17 at 7 12 00 AM" src="https://user-images.githubusercontent.com/678342/212935827-a08083ea-c94e-4421-8058-9490876ddc92.png">

**Comment by edigaryev** [comment] 2023-01-17 15:30
> Its faster (and bursty) but it hits 120MBps

It's bursty because the VM disk is uploaded in chunks of 512 MB, and it takes some time until TCP window size reaches the optimal value, hence the <>.

As for the speed, now we at least know that the Tart itself can achieve high speeds locally, the question is what preventing it from doing the same over the LAN/WLAN. 

A Wireshark traffic capture for a slow push session might give you some clues.

The other path is to keep running the experiment with the Docker Registry by moving it further away from your Mac each step, essentially nailing down the place where it starts to get really slow.

For example, if you have another machine at hand, plug the Mac and that machine (running Docker Registry) into the same network physically or via Wi-Fi to see if this gives you different results.

**Comment by hokadiri** [comment] 2023-01-17 15:36
Actually, its not faster using `VirtuoFS`. osxfs is a bit faster

<img width="716" alt="Screenshot 2023-01-17 at 7 20 12 AM" src="https://user-images.githubusercontent.com/678342/212937689-1dcba653-94c1-4afd-86d7-a18561956776.png">

<img width="804" alt="Screenshot 2023-01-17 at 7 19 45 AM" src="https://user-images.githubusercontent.com/678342/212937897-9b22932a-0984-4928-b9e9-2f8b30548047.png">

Using osfx
```
$ time tart push --insecure macos-ventura-xcode 127.0.0.1:5000/macos-ventura-xcode:latest
pushing macos-ventura-xcode to 127.0.0.1:5000/macos-ventura-xcode:latest...
pushing config...
pushing disk... this will take a while...
100%
pushing NVRAM...
pushing manifest for latest...
tart push --insecure macos-ventura-xcode   30.91s user 21.68s system 25% cpu 3:25.01 total
```

Using VirtuoFS
```
$  time tart push --insecure macos-ventura-xcode 127.0.0.1:5000/macos-ventura-xcode:latest
pushing macos-ventura-xcode to 127.0.0.1:5000/macos-ventura-xcode:latest...
pushing config...
pushing disk... this will take a while...
100%
pushing NVRAM...
pushing manifest for latest...
tart push --insecure macos-ventura-xcode   30.97s user 23.60s system 23% cpu 3:54.88 total
```

**Comment by hokadiri** [comment] 2023-01-17 17:32
Does `tart push` use any docker client configs under the hood?
i.e is it beneficial to have `docker desktop` installed in order to optimize tart pushes?
@edigaryev

**Comment by edigaryev** [comment] 2023-01-17 20:30
> Does `tart push` use any docker client configs under the hood?

It only uses `~/.docker/config.json` to [get credentials](https://github.com/cirruslabs/tart/blob/main/Sources/tart/Credentials/DockerConfigCredentialsProvider.swift) for registries it connects to.

> i.e is it beneficial to have `docker desktop` installed in order to optimize tart pushes?

No.

**Comment by hokadiri** [comment] 2023-01-17 20:45
Is there an equivalent docker push/pull cmd? this [docker pull](https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-ventura-xcode)  returns  `operating system is not supported`

**Comment by hokadiri** [comment] 2023-01-17 20:46
Can we reoi

**Comment by edigaryev** [comment] 2023-01-18 08:18
> Is there an equivalent docker push/pull cmd? this [docker pull](https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-ventura-xcode) returns `operating system is not supported` on an M1

Unfortunately, Tart OCI images are not compatible with Docker.

**Comment by hokadiri** [comment] 2023-01-18 17:20
Ok. 
If I have a faster way to move the `~/.tart` folder from `computer A` to `computer B`. Is that a workaround to the tart push slowness?

**Comment by fkorotkov** [comment] 2023-01-19 18:56
It's defiantly a workaround but it might not always work because you might end up with two VMs with the same MAC address which will break networking if you run both of them in parallel. For such bundle manipulations there is #370 which will allow to bundle a VM and handle MAC address uniqueness upon an export.

Regarding the possible issue, I suspect you are trying to push a VM from you laptop? Are you on VPN? Do you have any malware detection software installed by IT? Malware detection software might drastically slower applications if they are not added to a list of trusted applications.

**Comment by hokadiri** [comment] 2023-01-21 01:19
>I suspect you are trying to push a VM from you laptop?

Yes

>  Are you on VPN? 

Yes

>  Do you have any malware detection software installed by IT?

Yes. I'll confirm this

**Comment by hokadiri** [comment] 2023-02-02 17:02
Hey @fkorotkov, we're not doing anything to allow/denylist a tart. It may be network related.

**Comment by fkorotkov** [comment] 2023-02-05 19:58
`0.37.0` version now has a `import`/`export` commands to make bundles that you can transfer to other machines using any other option: torrent, S3, GCS, etc. 

Closing this issue since we are suspecting that the issue is with something else but Tart (local registry performs as expected).

**Closed by fkorotkov** 2023-02-05 19:58 UTC
Labels: bug, question
