### ISSUE TITLE
tart push gets terminated on a large image

### ISSUE THREAD

**Issue by victor-yousician** [cirruslabs/tart#165] opened 2022-08-01 14:29 UTC
I set disk size to 200GB
`tart set monterey-base --disk-size 200
`
, extended the disk in the OS
`diskutil apfs resizeContainer disk2 0
`
and pushed the resulting image to ghcr.io and local docker registry. Both tart push commands got terminated with a generic 
`zsh: killed
`
message. From what I see they ran out of memory. I am running this on MacBook Air with only 8GB of memory. Haven't had a chance to see how 32GB memory affects this yet.
Updated: works fine on 32GB. Activity Monitor reports over 50GB memory usage by `tart` process, but it doesn't crash.

**Comment by fkorotkov** [comment] 2022-08-01 15:23
I think #159 should help with that matter. Let's wait for it to get merged and released.

**Comment by edigaryev** [comment] 2022-08-01 23:39
Please try out the [new 0.17.0 version](https://github.com/cirruslabs/tart/releases/tag/0.17.0) to see if it fixes the issue for you.

**Comment by victor-yousician** [comment] 2022-08-02 07:09
I've just tried 0.17.0 - it does not fix the issue, tart still runs out of memory and is killed, but it does bring CPU usage down significantly.

**Comment by victor-yousician** [comment] 2022-08-08 06:25
Sorry to bug you, but I'm anxiously waiting to try #159. The outcome will decide if I need to request a beefier Mac.

**Comment by fkorotkov** [comment] 2022-08-08 14:57
@victor-yousician we are still not sure about the root cause. Our guess is that there is a memory leak in the https://github.com/swift-server/async-http-client library that Tart is using for HTTP requests.

We've just release `0.18.0` version with chunked uploads but also with a the latest version of `async-http-client` which by itself might fix your issue. 

If you up for some testing you can try a regular monolithic upload as before with `0.18.0` version which might work just because of the library update.

**Comment by victor-yousician** [comment] 2022-08-12 08:28
> If you up for some testing you can try a regular monolithic upload as before with `0.18.0` version which might work just because of the library update.

I tried monolithic upload and various chunk sizes (16MB-1024MB) - it makes no difference. Around 96% mark `tart` memory usage balloons and it's terminated.

**Comment by edigaryev** [comment] 2022-08-12 13:07
> > If you up for some testing you can try a regular monolithic upload as before with `0.18.0` version which might work just because of the library update.
> 
> I tried monolithic upload and various chunk sizes (16MB-1024MB) - it makes no difference. Around 96% mark `tart` memory usage balloons and it's terminated.

Could you please share which macOS version you're using and the output of `otool -L $(which tart)` command (it the versions of dynamic libraries that will be used by Tart once it's loaded)?

**Comment by victor-yousician** [comment] 2022-08-12 13:19
```
administrator@jenkins-m1-node ~ % uname -a                                                                                           
Darwin jenkins-m1-node.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
administrator@jenkins-m1-node ~ % otool -L $(which tart)
/opt/homebrew/bin/tart:
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.32.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2266.14.0)
	/System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork (compatibility version 1.0.0, current version 1385.0.0)
	/System/Library/Frameworks/Combine.framework/Versions/A/Combine (compatibility version 1.0.0, current version 308.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1940.0.0)
	/System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1940.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60420.0.73)
	/System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI (compatibility version 1.0.0, current version 4.0.78)
	/System/Library/Frameworks/Virtualization.framework/Versions/A/Virtualization (compatibility version 1.0.0, current version 101.4.0)
	/usr/lib/swift/libswiftAppKit.dylib (compatibility version 1.0.0, current version 110.0.0, weak)
	/usr/lib/swift/libswiftCompression.dylib (compatibility version 1.0.0, current version 6.0.0)
	/usr/lib/swift/libswiftCore.dylib (compatibility version 1.0.0, current version 5.7.0)
	/usr/lib/swift/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 120.100.0, weak)
	/usr/lib/swift/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 14.0.0, weak)
	/usr/lib/swift/libswiftCoreImage.dylib (compatibility version 1.0.0, current version 2.0.0, weak)
	/usr/lib/swift/libswiftDarwin.dylib (compatibility version 1.0.0, current version 0.0.0)
	/usr/lib/swift/libswiftDispatch.dylib (compatibility version 1.0.0, current version 17.0.0)
	/usr/lib/swift/libswiftIOKit.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
	/usr/lib/swift/libswiftMetal.dylib (compatibility version 1.0.0, current version 306.1.8, weak)
	/usr/lib/swift/libswiftNetwork.dylib (compatibility version 1.0.0, current version 3013.0.52)
	/usr/lib/swift/libswiftOSLog.dylib (compatibility version 1.0.0, current version 4.0.0, weak)
	/usr/lib/swift/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 6.0.0)
	/usr/lib/swift/libswiftQuartzCore.dylib (compatibility version 1.0.0, current version 3.0.0, weak)
	/usr/lib/swift/libswiftUniformTypeIdentifiers.dylib (compatibility version 1.0.0, current version 747.0.0, weak)
	/usr/lib/swift/libswiftVirtualization.dylib (compatibility version 1.0.0, current version 101.4.0)
	/usr/lib/swift/libswiftXPC.dylib (compatibility version 1.0.0, current version 6.0.0, weak)
	/usr/lib/swift/libswift_Concurrency.dylib (compatibility version 1.0.0, current version 5.7.0)
	/usr/lib/swift/libswiftos.dylib (compatibility version 1.0.0, current version 1033.0.0, weak)
	/usr/lib/swift/libswiftFoundation.dylib (compatibility version 1.0.0, current version 1.0.0)

```

**Comment by edigaryev** [comment] 2022-08-12 15:03
Unfortunately I am unable to reproduce the issue you're facing: the memory usage always stays in the 0.5-2.76 GB range. Regarding the information you've posted above, the only difference I've found with my system is that I'm running macOS 12.5, not 12.4.

I think to nail this down we'll have to exclude some unknowns.

Can you confirm that pushing a freshly pulled [`ghcr.io/cirruslabs/macos-monterey-base:latest`](https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-monterey-base) results in a significant RAM usage when re-pushed to a locally running Docker Registry, started according to the instructions below?

Start a Docker Registry on `:8080` while being in a scratch directory:

```
docker run -it --rm -p 8080:5000 -v $(pwd):/var/lib/registry registry:2
```

Re-push the image:

```
tart push --insecure ghcr.io/cirruslabs/macos-monterey-base:latest 127.0.0.1:8080/a:b
```

**Comment by victor-yousician** [comment] 2022-08-13 17:18
This is pretty close to my setup, but I have the registry running natively, not in a container. Pushing freshly pulled image works fine, it's only when I extend the disk to 200GB I get this issue. Extending the disk to 120GB worked too, if I remember correctly. Pushing to a remote registry (I tried with ghcr.io) made no difference (besides speed, of course). Again, no issues on my dev machine with 32GB of RAM, only on the POC Jenkins node with just 8GB.

**Closed** 2022-08-17 16:57 UTC
Labels: bug
