### ISSUE TITLE
UnexpectedHTTPStatusCode when pushing an image to a remote registry

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [cirruslabs/tart#120] opened 2022-06-08 13:58 UTC
Incredibly helpful tool, thank you for working on this project, this is amazing.
I am able to pull things from your remote (ghcr.io/cirruslabs/macos-monterey-base:latest) to create an image locally and then can run it with `tart run`.

Trying to push the local image to a remote fails with a generic error message:

```
$ tart push monterey-base-ci my-remote.host/docker-local-dev/macos/macos-monterey-ci:v1.0.0
pushing monterey-base-ci to my-remote.host/docker-local-dev/macos/macos-monterey-ci:v1.0.0...
UnexpectedHTTPStatusCode(when: "pushing blob (PUT)", code: 404, details: "")
```

Is there any way to get more info about the communication between `tart` and the remote registry to troubleshoot?

I have ran `tart login` providing my credentials and the command exited with the code 0.

**Comment by edigaryev** [comment] 2022-06-08 14:18
I've created a PR (https://github.com/cirruslabs/tart/pull/121) that should help with diagnosing this.

What OCI container registry software are you running? Is there a way to reproduce this somehow (e.g. the registry is publicly available)?

**Comment by alexey-tereshenkov-oxb** [comment] 2022-06-08 14:22
Thanks for taking a look. Extra verbosity would indeed be helpful, I'd love to avoid tracing the network packets :) it's a private instance of Artifactory. I am able to push/pull Docker images. They [claim](https://www.jfrog.com/confluence/display/JFROG/Docker+Registry) to be OCI compatible

> OCI Support
Artifactory is OCI compliant and supports OCI clients, enabling you to deploy and resolve OCI images in Docker Registries. The OCI client Singularity is not supported.

so experimenting to see what's necessary to do on the client side to be able to push/pull tart-based images (and if the Artifactory is not happy accepting the binaries, what kind of configuration of the Artifactory would be required).

Cheers,

**Comment by edigaryev** [comment] 2022-06-08 14:33
> Artifactory

Interesting! I've just tried pushing a VM to a cloud Artifactory instance and it all went smooth.

Please check out the [new 0.8.2 release)(https://github.com/cirruslabs/tart/releases/tag/0.8.2) which includes the changes from #121.

**Comment by alexey-tereshenkov-oxb** [comment] 2022-06-08 14:35
FWIW https://www.jfrog.com/confluence/display/RTF4X/Getting+Started+with+Docker+and+Artifactory#GettingStartedwithDockerandArtifactory-GettingStartedwithArtifactoryasaDockerContainer running Artifactory in a Docker container for testing

**Comment by alexey-tereshenkov-oxb** [comment] 2022-06-08 16:12
With the new version I get


```
$ tart push monterey-base-ci remote-host/docker-local-dev/macos/macos-monterey-ci:v1.0.0

pushing monterey-base-ci to remote-host/docker-local-dev/macos/macos-monterey-ci:v1.0.0...
UnexpectedHTTPStatusCode(when: "pushing blob (PUT) to https://remote-host/v2/docker-local-dev/macos/macos-monterey-ci/blobs/uploads/d844faf4-6ec8-48a9-b3c1-1909b8d28015", code: 404, details: "")
```

Not sure if that's helpful at all? Navigating to the link gives this browser:

```
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

I confirm I can pull and push Docker images from/to the Artifactory instance (the command is run on the same machine from where I run `tart` and I've used the same credentials to login with `docker login` as I did with `tart login`).

Thanks.

**Comment by edigaryev** [comment] 2022-06-08 19:15
@alexey-tereshenkov-oxb which Artifactory version are you running?

**Comment by alexey-tereshenkov-oxb** [comment] 2022-06-08 20:18
Thanks a lot chaps for giving a hand with this, very kind of you.

> @alexey-tereshenkov-oxb which Artifactory version are you running? I've tried the on-premise version 7.38.7 and it also works fine.
> 
> However, the old versions seem to be completely broken w.r.t. container registry specification, even the official Docker client complains when their an image from an official JFrog's registry:
> 
> <img alt="Screenshot 2022-06-08 at 22 08 04" width="607" src="https://user-images.githubusercontent.com/85709/172701970-41fd0291-dbff-48a9-bb8e-22dc7a742049.png">

Mine is a bit old, 6.17.0. This could be the issue indeed.

I've tried setting up the latest locally from https://jfrog.com/artifactory/install/, but the instructions are available in multiple places and contradict each other, e.g. https://www.jfrog.com/confluence/display/RTF4X/Getting+Started+with+Docker+and+Artifactory#GettingStartedwithDockerandArtifactory-GettingStartedwithArtifactoryasaDockerContainer.

I'll persevere for a bit longer and if I fail, will try to get the Artifactory upgraded to a more recent version.

**Comment by edigaryev** [comment] 2022-06-08 20:21
> but the instructions are available in multiple places and contradict each other

I've installed the latest version following the instructions [on this page](https://jfrog.com/artifactory/install/), the Confluence document seems to be outdated for the newer versions of Artifactory.

**Comment by edigaryev** [comment] 2022-06-16 08:59
Closing because the underlying issue is related to the outdated Artifactory software, which doesn't implement the OCI distribution specification properly.

@alexey-tereshenkov-oxb please reopen if this issue re-surfaces for you on the newer versions of the Artifactory.

**Closed as completed by edigaryev** 2022-06-16 09:00 UTC
