### ISSUE TITLE
Potential caveat in 'tart ip ...'

### ISSUE THREAD

**Issue by remarkov** [cirruslabs/tart#172] opened 2022-08-04 16:41 UTC
When using one of the VMs for a while I noticed that `tart ip ...` command returns incorrect IP address, no matter whether VM is running or not I'm getting the same incorrect IP. In VM I see the IP address is 192.168.65.4 but `tart ip` command always returns 192.168.64.34. Here's how it looks like:
```
$ tart ip base
192.168.64.34

$ cat .tart/vms/base/config.json | grep macAddress
  "macAddress" : "ee:a7:85:09:92:39",
```

I checked the [code](https://github.com/cirruslabs/tart/blob/main/Sources/tart/Commands/IP.swift) and see that IP address is determined from `/var/db/dhcpd_leases` and here's where the error comes from indeed:
```
$ cat /var/db/dhcpd_leases | grep $(tart ip base) -A 1
	ip_address=192.168.64.34
	hw_address=1,ee:a7:85:9:92:39
```
And this record is there even when the VM is shut down. Most likely it is some leftover from the Anka VMs that were also used on the same host previously and somehow got the same MAC address, so `tart ip base` returns that IP address even if the VM is not actually running.

I also noticed that [initially](https://github.com/cirruslabs/tart/pull/8) you were parsing the IP address from `arp` output and indeed, that would give the proper result in this case:
```
$ arp -an
...
? (192.168.65.4) at ee:a7:85:9:92:39 on bridge100 ifscope [bridge]
...
```
This is the correct IP address of the Tart VM.

Not saying you need to revert to `arp` approach of getting the IP address but maybe you might consider improving this logic. 

Maybe it is just a rare coincidence and if someone stumbles upon the same issue they might just clean up their `/var/db/dhcpd_leases` which helps of course.

Thanks!

**Comment by fkorotkov** [comment] 2022-08-04 16:47
I think to eliminate any potential corrupted state from the previous use of the virtualization framework you can try to clone you r local image into a new one. This way you'll force a new unique machine identity.

But I'll let @edigaryev to weight in since he is the guru of networking. 😅

**Comment by remarkov** [comment] 2022-08-04 16:54
Yes, cloning should also help of course but again there's a chance that if you get a MAC that matches another one in your leases DB that would get you the same issue. It appears MAC addresses are not very unique in Apple Virtualization and the DB might also be clogged with some old stuff which will interfere with the `tart ip` command.

**Comment by edigaryev** [comment] 2022-08-05 07:39
Is your Tart VM using a static IP?

It looks like the VM has managed to receive an IP without consulting with the DHCP daemon, which should've either assigned the lease that matches the VM's MAC or gave you a new one.

Regarding the ARP cache scraping, we've decided to switch to the DHCP leases parsing instead as the [Softnet](https://github.com/cirruslabs/softnet) extension for Tart uses macOS DHCP server database in it's security model and this might move might help with early bug(s) discovery.

**Comment by edigaryev** [comment] 2022-08-12 13:50
@remarkov just a little nudge to say that you will really help with resolving this by providing some more details, see https://github.com/cirruslabs/tart/issues/172#issuecomment-1206144115. I've tried reproducing your case by artificially altering the DHCP leases file, but wasn't able to arrive at the same result as yours.

@fkorotkov I'm thinking of bringing back the `arp` command approach, but only for the sake of warning the user that something is going wrong. What do you think?

**Comment by remarkov** [comment] 2022-08-12 17:07
@edigaryev sorry I missed your previous comment here. I will be happy to help as much as I can.

> Is your Tart VM using a static IP?

no, it's configured to DHCP. what I also noticed when this issue occurred is that somehow I've got two different records in DHCP leases file with different IP addresses but the same MAC address. and obviously `tart ip` command got only one of them, don't remember was it the first or the last record. I'm not sure how exactly did that happened, most likely the other record was added by Anka which was running on this host before we switched to Tart. I've cleared up the DHCP lease file entirely and the issue never happened since that time but I'm concerned that the file is growing as I run more VMs on this host and I'm not sure what is the proper logic (if any) to "purge" it after VMs got discarded.

in my use case I have this "golden template" VM which is in shut down state and every time I need to run some job on a VM I clone that template VM to a temporary one (which gets an new IP every time I do the clone of course), use the VM and then kill it.

hope this helps!

> I'm thinking of bringing back the arp command approach, but only for the sake of warning the user that something is going wrong.

I personally think that would be the best and safe solution.

**Comment by fkorotkov** [comment] 2022-08-15 14:21
Just a note that if you "golden template" will be a remote template than a clone into a local VM won't generate a new Mac and therefore there will no new IP. On the DHCP side if I recall correctly the leases are 24 hours and if you don't run more than 256 VMs in 24 hours than it should be fine. @edigaryev please correct me if I'm wrong.

**Closed** 2022-08-18 18:25 UTC
Labels: question

**Comment by mcaulifn** [comment] 2022-11-23 13:57
@fkorotkov Is this still an on-going issue? I'm trying to run packer and packer is never able to connect to the VM. A reboot of the host "fixed" the issue once. Now I'm getting this:

```
packer build -on-error=ask .
base.tart-cli.base: output will be in this color.

==> base.tart-cli.base: Cloning virtual machine...
==> base.tart-cli.base: Updating virtual machine resources...
==> base.tart-cli.base: Inspecting machine disk image...
==> base.tart-cli.base: Getting partition table...
==> base.tart-cli.base: Starting the virtual machine...
==> base.tart-cli.base: Waiting for the VNC server credentials from Tart...
==> base.tart-cli.base: Retrieved VNC credentials, connecting...
==> base.tart-cli.base: Connected to the VNC!
==> base.tart-cli.base: Typing the commands over VNC...
==> base.tart-cli.base: Successfully started the virtual machine...
==> base.tart-cli.base: Using SSH communicator to connect: 192.168.65.4
==> base.tart-cli.base: Waiting for SSH to become available...

<in different window>

tart ip tart-xcode-14
WARNING: DHCP lease and ARP cache entries for MAC address 6a:47:e3:87:a1:93 differ: got 192.168.65.4 and 192.168.68.2 respectively, consider reporting this case to https://github.com/cirruslabs/tart/issues/172
192.168.65.4
```

**Comment by edigaryev** [comment] 2022-11-23 14:04
@mcaulifn have you used Anka on the same machine before?

You try moving the `/var/db/dhcpd_leases` somewhere else (or just completely removing it) to see if it fixes the issue.
