### ISSUE TITLE
Cannot start VM w/ Bridged Networking

### ISSUE THREAD

**Issue by paragchandra** [cirruslabs/tart#424] opened 2023-02-21 21:15 UTC
I'm trying to start a VM with bridged networking, like this:

`tart run ventura-base --net-bridged=en0`

That fails with `Error: Invalid virtual machine configuration. Using VZBridgedNetworkDeviceAttachment in a process that lacks the “com.apple.vm.networking” entitlement.`

Then I tried `sudo tart run ventura-base --net-bridged=en0`

but that fails with `the specified VM "ventura-base" does not exist`

What is the recommended way of starting a VM with bridged networking? I'm running Ventura 13.2.1 and tart 0.37.2 on an M1 Macbook Pro.

**Comment by fkorotkov** [comment] 2023-02-21 21:20
Duplicate of #243. Unfortunately bridged network is not fully supported yet. There are some difficulties that we need to repack Tart as an `.App` in order to the entitlements to work. 😪

**Closed by fkorotkov** 2023-02-21 21:20 UTC

**Comment by paragchandra** [comment] 2023-02-21 21:53
Right, I just found that duplicate and came here to close out my issue. Sorry!

**Comment by fkorotkov** [comment] 2023-02-22 13:07
No worries. We should probably don't show the flag for now. Fixing it in #425.
