### ISSUE TITLE
tart clone creates a link, which doesn't work when TART_HOME is an external drive.

### ISSUE THREAD

**Issue by magnusviri** [cirruslabs/tart#226] opened 2022-09-05 22:07 UTC
Setup:

```
export TART_HOME=/Volumes/autopkg/tart
tart clone ghcr.io/cirruslabs/macos-monterey-base:latest autopkg
```
Error

```
Error Domain=NSCocoaErrorDomain Code=512 "The file “autopkg” couldn’t be saved in the folder “vms”." UserInfo={NSFileOriginalItemLocationKey=file:///Volumes/autopkg/tart/vms/autopkg/, NSURL=file:///Volumes/autopkg/tart/vms/autopkg/, NSFileNewItemLocationKey=file:///var/folders/m9/pqzn80q548z2419lljbgydh40000gp/T/51270D9E-C92F-45F3-B026-97B286457FFE, NSUnderlyingError=0x6000034fa820 {Error Domain=NSCocoaErrorDomain Code=512 "The file “51270D9E-C92F-45F3-B026-97B286457FFE” couldn’t be saved in the folder “T”." UserInfo={NSURL=file:///var/folders/m9/pqzn80q548z2419lljbgydh40000gp/T/51270D9E-C92F-45F3-B026-97B286457FFE, NSFilePath=/var/folders/m9/pqzn80q548z2419lljbgydh40000gp/T/51270D9E-C92F-45F3-B026-97B286457FFE, NSUnderlyingError=0x6000034fa670 {Error Domain=NSPOSIXErrorDomain Code=18 "Cross-device link"}}}}
```

I will try `tart create` now.

**Comment by magnusviri** [comment] 2022-09-05 22:21
I also tried this and it gave me the exact same error.

```
export TART_HOME=/Volumes/autopkg/tart
tart create --from-ipsw=latest autopkg
```

Note, both commands I just tried is what led to the "[No space left on device](https://github.com/cirruslabs/tart/issues/222)" error.

**Comment by magnusviri** [comment] 2022-09-05 22:30
Finally, to be completely thorough, I copied a tart home that contained a VM created on another computer to the external drive and it worked. It was slow though because the drives are slow. I'll have to get faster drives.

I tried to clone that one and it has the same exact behavior, putting it in DARWIN_USER_TEMP_DIR and then trying to cross-device link it.

**Comment by edigaryev** [comment] 2022-09-05 22:59
Indeed, `rename(2)` doesn't work across volumes and returns `EXDEV`.

Closing as a duplicate of #222, the temporary directory issue will be resolved there.

**Closed by edigaryev** 2022-09-05 22:59 UTC
