### ISSUE TITLE
Snapshots to be able to reset tart VMs to a desired starting point 

### ISSUE THREAD

**Issue by TK5-Tim** [cirruslabs/tart#213] opened 2022-08-30 14:29 UTC
It would be very beneficial to have a possibility to set the vm back to a previously determined status without having to create a whole new tart VM. 

Currently the only way is to do this is by creating a custom snapshot via time machine and restored via the recovery.

**Comment by edigaryev** [comment] 2022-08-30 15:23
Hello Tim!

This looks like a duplicate of https://github.com/cirruslabs/tart/issues/147.

`Virtualization.Framework` doesn't provide such functionality right now, but it's possible it will be implemented in the future, so stay tuned.

**Closed by edigaryev** 2022-08-30 15:23 UTC
