### ISSUE TITLE
VM is not getting assigned an IP address

### ISSUE THREAD

**Issue by nickrttn** [cirruslabs/tart#632] opened 2023-10-17 08:15 UTC
I'm running an Ubuntu 22.10 VM on a macOS Sonoma host, with these executables:

- `tart@2.1.0`
- `softnet@0.7.2`

and the following command: `tart run --rosetta=rosetta --net-softnet --vnc-experimental --dir=api:… --dir=web:… <vm-name>`

Up until recently, everything was peachy and my VM would always get an IP address (although only using `softnet`, regular NAT doesn't work for me).

But now, `tart ip <vm-name>` returns `no IP address found`, and running `ip addr` in the guest VM also yields no configured IPv4 address.

I'm not sure where to start troubleshooting this.

**Comment by nickrttn** [comment] 2023-10-17 12:52
I start/stop about once per day, more often if I run into any issues that need a reboot, like a kernel panic or a broken mount. No VPN, no custom setup on my host machine.

**Comment by edigaryev** [comment] 2023-10-17 13:50
> I'm not sure where to start troubleshooting this.

1. Does it happen with the macOS too?
2. Does it happen when using the`ghcr.io/cirruslabs/ubuntu:22.04` image?

**Comment by nickrttn** [comment] 2023-10-17 15:08
> Does it happen with the macOS too?

My macOS host receives IP addresses just fine from my router, unless you are talking about a macOS guest. I don't use one of those.

> Does it happen when using the `ghcr.io/cirruslabs/ubuntu:22.04` image?

I'll try it and report back

**Comment by edigaryev** [comment] 2023-10-17 15:21
>Yes, it also happens when using the ghcr.io/cirruslabs/ubuntu:22.04 image.

Even if you `tart run` it's clone without any additional arguments?

Could you try stopping all VMs, removing the `/var/db/dhcpd_leases` file (or moving it somewhere else temporarily, elevated privileges will be needed) to see if it fixed the issue?

Also, have you used (or using) other VM solutions on this machine?

**Comment by nickrttn** [comment] 2023-10-17 15:38
I executed `tart run --rosetta=rosetta --vnc-experimental ubuntu`, do you expect those two flags to be an issue?

I have had both Docker and Parallels installed, but have uninstalled both.

**Comment by nickrttn** [comment] 2023-10-17 15:41
I had removed `/var/db/dhcpd_leases` earlier today, below is the response I get now. Have started a VM several times between removing the file earlier and trying to remove the file again.

```sh
λ sudo rm /var/db/dhcpd_leases
rm: /var/db/dhcpd_leases: No such file or directory
```

**Comment by fkorotkov** [comment] 2023-10-19 11:19
It's weird you don't have `/var/db/dhcpd_leases`. 🤔 Are you sure there is no software that could interfere? 

Also could you please try Bridged network with `--net-bridged` flag? Note that you'll need to use Arp resolver to get an IP: `tart ip --resolver=arp ubuntu`

**Comment by nickrttn** [comment] 2023-10-19 13:49
> It's weird you don't have `/var/db/dhcpd_leases`

I did remove it earlier that day, but even now when I check it wasn't recreated 🤔 

Also could you please try Bridged network with `--net-bridged` flag? Note that you'll need to use Arp resolver to get an IP: `tart ip --resolver=arp ubuntu`

I do get an IP address, evidently given out by my router, when I use `--net-bridged`, as reported by `ip addr` inside the VM. `tart ip --resolver=arp ubuntu` returns `no IP address found (not all Linux distributions are compatible with the ARP resolver)`

**Comment by fkorotkov** [comment] 2023-11-08 15:37
Closing since there is no repro and from symptoms like missing `/var/db/dhcpd_leases` looks like a machine configuration issue.

**Closed by fkorotkov** 2023-11-08 15:37 UTC
Labels: bug, question

**Comment by aduh95** [comment] 2023-11-22 10:06
FWIW I'm also able to reproduce this. The only recent system change I can think of is the upgrade to macOS 14. `/var/db/dhcpd_leases` exists on my host OS. I do have a VPN installed on my host OS, so I tried quitting it before I launched my VM, but that didn't change anything.

I managed to resolve the problem by editing out of `/var/db/dhcpd_leases` the info related to the VM, and start it off again, and that solved the issue. It seems that the IP address has changed (it used to be `192.168.64.2`, and is now `192.168.65.2`), I wonder if the issue was that `tart` was reporting the wrong IP address for some reason.

**Comment by edigaryev** [comment] 2023-11-22 10:11
@aduh95 next time you experience this please check the IP address actually assigned inside of a VM, if it looks like `169.254.*.*` (see https://github.com/cirruslabs/tart/issues/657), you might try applying https://github.com/cirruslabs/tart/issues/657#issuecomment-1812129793 to see if it fixes the problem.
