### ISSUE TITLE
halt/stop command

### ISSUE THREAD

**Issue by tomjn** [cirruslabs/tart#298] opened 2022-11-04 15:19 UTC
Currently you can execute `tart run` however there is no way to stop this VM via a command either in the current shell or in another shell on the same system. It's also unclear how you would track the current status of the VM wether it was running or idle.

So, in addition to `tart run`, it would be nice to have a `tart stop` similar to `vagrant halt`. This would send a shutdown signal to the VM requesting it powerdown/exit gracefully. Ideally an additional parameter could be provided for a more forceful/bruteforce termination of the VM process

**Comment by fkorotkov** [comment] 2022-11-06 00:31
For the CLI use case Tart was designed to not have a daemon running somewhere. This way consumers are responsible for killing tart process which will gracefully shutdown the VM. Hopefully vagrant can track own a process between `vagrant up` and `vagrant halt`?

**Comment by tomjn** [comment] 2022-11-06 02:43
hmmm it's not necessarily that a tart service or daemon needs to sit and actively monitor running VMs, though that is one way of doing it. Rather that vagrant itself is not a long running task. If Tart doesn't have some notes somewhere saying VM 1 is turned on with this PID then that means that running a command such as `tart stop ubuntu` to trigger the process exit will be difficult and there'll need to be some logic to do all of the housekeeping locally.

The downside of doing the housekeeping locally is that you then have to double check Tart exited gracefully and that the PID didn't get reused for something else.

**Comment by tomjn** [comment] 2022-11-06 18:20
Confirmed that you can SSH into a tart Linux VM and run `sudo shutdown now` to halt the machine.

Tart will show:

```
❯ tart run ubuntu
guest has stopped the virtual machine

```

It does require passwords entering but that's a configuration issue to add passwordless sudo.

**Comment by tomjn** [comment] 2022-11-06 18:22
The remaining problem is that it's not possible to do this simple set of commands if a vagrant provider was built:

```sh
# turn it on:
vagrant up <-- this command would never exit
# turn it off:
vagrant halt
```

**Comment by ringods** [comment] 2022-11-06 18:47
@tomjn something which came to mind: could the vagrant tart plugin spawn a child process when running `vagrant up`, so you decouple core Vagrant from the Tart specific handling? Core vagrant could then return as usual for `vagrant up`. At `vagrant halt`, the tart plugin could check for its own child process and signal termination.

**Comment by edigaryev** [comment] 2022-11-11 07:59
Closing because this has been resolved by https://github.com/cirruslabs/tart/pull/316.

**Closed by edigaryev** 2022-11-11 07:59 UTC
