### ISSUE TITLE
Simulated clipboard paste 

### ISSUE THREAD

**Issue by bossprocedure** [cirruslabs/tart#715] opened 2024-01-21 14:59 UTC
It would be of great help to have clipboard paste-like functionality in non-networked scenarios. Many remote clients (e.g. VNC) simulate this by reading the clipboard and sending per-character keystrokes to the VM.

**Comment by fkorotkov** [comment] 2024-01-22 13:44
Duplicate of #14. It's not possible at the moment for macOS guests.

**Closed by fkorotkov** 2024-01-22 13:44 UTC
