### ISSUE TITLE
Error: dataCorrupted while cloning image

### ISSUE THREAD

**Issue by NickBouwhuis** [cirruslabs/tart#851] opened 2024-06-29 17:47 UTC
Hello,

I am trying to clone the `macos-sequoia-vanilla:15` image but get this error:

```
❯ tart clone ghcr.io/cirruslabs/macos-sequoia-vanilla:15 macos-sequoia-vanilla
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "hardwareModel", intValue: nil)], debugDescription: "", underlyingError: nil))
```

This occurs after downloading the whole image. 

Here is the list of all images on my system (including the hash)
```
❯ tart list
Source Name                                                                                                             Disk Size State
OCI    ghcr.io/cirruslabs/macos-sequoia-vanilla:15.0                                                                    50   20   stopped
OCI    ghcr.io/cirruslabs/macos-sequoia-vanilla:latest                                                                  50   20   stopped
OCI    ghcr.io/cirruslabs/macos-sequoia-vanilla@sha256:8d45fd41bfe2d1dd209de4d0542ac6f9e64bcc7f84cd2eb763ddbcea10d23424 50   20   stopped
```

What would cause this? Is there something wrong with my system or the image?

**Comment by edigaryev** [comment] 2024-07-01 11:27
It seems that the Apple had bumped the `DataRepresentationVersion` in `hardwareModel`.

Here's a decoded `hardwareModel` from `ghcr.io/cirruslabs/macos-sonoma-base:latest`:

```
{
  "DataRepresentationVersion" => 1
  "MinimumSupportedOS" => [
    0 => 13
    1 => 0
    2 => 0
  ]
  "PlatformVersion" => 2
}
```

And this is a decoded `hardwareModel` from `ghcr.io/cirruslabs/macos-sequoia-vanilla:15.0`:

```
{
  "DataRepresentationVersion" => 2
  "MinimumSupportedOS" => [
    0 => 13
    1 => 0
    2 => 0
  ]
  "PlatformVersion" => 2
}
```

@fkorotkov I wonder if we need to start building Tart on macOS Sequoia 🤔

**Comment by fkorotkov** [comment] 2024-07-01 15:32
The image just got rebuild on a Sonoma host so it should be fixed.

**Closed** 2024-07-01 15:31 UTC

**Comment by iby** [comment] 2024-08-20 17:55
I'm seeing the exact same thing on the latest Sonoma… am I missing something? Or has something changed recently? 🤔

```
tart clone ghcr.io/cirruslabs/macos-sequoia-vanilla:15.1 seq --concurrency 10
pulling manifest...
pulling disk (17.9 GB compressed)...
100%
pulling NVRAM...
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "hardwareModel", intValue: nil)], debugDescription: "", underlyingError: nil))
```

**Comment by iby** [comment] 2024-08-20 18:43
P.S. The last image that works is [15.0-beta-3](https://github.com/orgs/cirruslabs/packages/container/macos-sequoia-vanilla/242403935?tag=15.0-beta-3), but [15.1-beta-1](https://github.com/orgs/cirruslabs/packages/container/macos-sequoia-vanilla/250962268?tag=15.1-beta-1) and [15.1-beta-2](https://github.com/orgs/cirruslabs/packages/container/macos-sequoia-vanilla/257447203?tag=15.1-beta-2) fail with the above error.

Using the tart 2.18.0.

**Comment by edigaryev** [comment] 2024-08-20 19:01
> Or has something changed recently? 🤔

Please see https://github.com/cirruslabs/tart/issues/883#issuecomment-2273236519.

**Comment by iby** [comment] 2024-08-21 07:07
Was hoping till the last moment that I could avoid building… 😅

**Comment by nholloh** [comment] 2024-12-13 11:01
@fkorotkov has this been resolved in recent versions of tart so that images can now be built from sequoia hosts? Our IT has recently updated all macs to sequoia, so the images built on these machines yield this error now.

**Comment by edigaryev** [comment] 2024-12-18 13:43
@nholloh

1. Which Sequoia version are you running on host?

2. Which Tart command are you invoking which results in the `dataCorrupted` error?

3. Which Tart version are you running (`tart --version`)?

**Comment by nholloh** [comment] 2024-12-18 14:54
1) 15.2

2) As defined in https://tart.run/integrations/gitlab-runner/ except for the following changes:
  [runners.custom]
    prepare_exec = "/opt/homebrew/bin/gitlab-tart-executor"
    prepare_args = ["prepare", "--concurrency", "2", "--cpu", "auto", "--memory", "auto"]
    run_exec = "/opt/homebrew/bin/gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "/opt/homebrew/bin/gitlab-tart-executor"
    cleanup_args = ["cleanup"]

3) 2.21.0

The images are custom images created from ipsw, after merging the packer configurations from your vanilla and base images. Let me know if providing the packer hcl files helps in diagnosing the issue.

**Comment by edigaryev** [comment] 2024-12-18 14:58
@nholloh

1. Which Tart VM image do you using in your GitLab CI configuration?

2. Can you try running `tart clone` locally on that GitLab Runner machine to see if it fails also?

3. Please provide an output of `tart fqn <VM image you're using>` command uniquely to identify the image.

**Comment by nholloh** [comment] 2024-12-18 15:13
1. its called `macos-sequoia-xcode-16-1`, which is based off our `macos-sequoia-15-0-1-base` version. The base image is created from the IPSW `https://updates.cdn-apple.com/2024FallFCS/fullrestores/072-01423/566E5B4E-1100-4643-91B3-131247351844/UniversalMac_15.0.1_24A348_Restore.ipsw`. The image is built on a host with sequoia 15.2 and tart 2.21.0. We're using artifactory to host the images. If you have a filedrop (or email) I can provide you with the exact configurations we're building.

2. (and 3) I need to ask our IT support to run the commands, since I don't have access to the host machines myself. Could take a bit. I'll get back to you asap.

**Comment by edigaryev** [comment] 2024-12-18 15:14
>I need to ask our IT support to run the commands, since I don't have access to the host machines myself. Could take a bit. I'll get back to you asap.

Oh, I thought this it's a public image maintained by Cirrus Labs, no need to run this command in case you're using a private VM image.

**Comment by nholloh** [comment] 2024-12-18 15:17
It is not, the image maintained by you works just fine on our runners. Our custom image does not. I realize the problem is entirely on our side, so I am trying to figure out what changed between sonoma and sequoia und what it is we're apparently doing differently from you.

**Comment by edigaryev** [comment] 2024-12-18 15:22
> I realize the problem is entirely on our side, so I am trying to figure out what changed between sonoma and sequoia and what it is we're apparently doing differently from you.

You can try building [`xcode.pkr.hcl`](https://github.com/cirruslabs/macos-image-templates/blob/master/templates/xcode.pkr.hcl) on your own infrastructure to see it will still work.

This could provide some clues.
