### ISSUE TITLE
The maximum supported number of active virtual machines has been reached.

### ISSUE THREAD

**Issue by jeff-h** [cirruslabs/tart#445] opened 2023-03-13 20:07 UTC
I keep getting the following error after a certain number of sequential (non-overlapping) tart runs (4 or 5, I think):

> "The maximum supported number of active virtual machines has been reached."

I understand Apple have built a limit into the VM framework, but the limit is for *simultaneously active* VMs, I think?

At first I thought I was possibly getting the error because I was killing the VMs each time by sending `ctrl+c` to my `tart run`’s from the command line, and consequently perhaps Tart was not cleaning up on exit, but even after restarting my host Mac and testing it again by doing a clean "Apple menu > Shut Down" inside the VM each time, the error still occurred after about four runs.

I'm interested to know if others are experiencing this? It's trivial to replicate, for me at least.

Also, is there any way to clean up and reset the counter other than restart the host Mac? Perhaps a process to kill in Activity Monitor?

**Comment by fkorotkov** [comment] 2023-03-13 20:25
@jeff-h we've never seen such behaviour. Which version of macOS you have on your host and what's `tart --version` is showing for you?

**Comment by jeff-h** [comment] 2023-03-13 20:27
I'm using macOS 13.2.1 & Tart 1.0.5

I just tested a similar sequence of startups with UTM and got to seven VM launches & quits without any sign of the error.

I then re-tested Tart to ascertain the exact number of successful launches before the error, and... no error 🙈

```sh
% tart run my-base
# here inside the VM I go to the Apple menu and choose Shut Down
guest has stopped the virtual machine
```
repeated 6 times, no error this time...

So either launching VMs in UTM first affected my results, or some other unknown factor is at play. I will keep an eye out for anything that can replicate this, but I guess you may have to just close this issue for now :(

**Comment by fkorotkov** [comment] 2023-03-13 20:34
Rodger that. Closing for now and let's reopen if you or someone else will reproduce it.

**Closed by fkorotkov** 2023-03-13 20:34 UTC

**Comment by leohidalgo** [comment] 2023-05-18 20:55
I have been able to reproduce it leaving a virtual machine running and putting the computer at sleep, after a few minutes when unlocking the computer, the virtual machine has disappeared and when trying to start another one I get the above message

**Comment by fkorotkov** [comment] 2023-05-18 20:59
@leohidalgo are you running it in headless mode (`tart run --no-graphics`)? Or you have a window open and it disappears? What does `tart list` show up? Does it show it as `Running`?

**Comment by leohidalgo** [comment] 2023-05-18 22:21
Window open and it disappears

**Comment by jeff-h** [comment] 2023-05-18 22:31
Hmm, can't replicate it [that way](https://github.com/cirruslabs/tart/issues/445#issuecomment-1553632091) myself unfortunately.

**Comment by olejnjak** [comment] 2023-12-14 12:06
I don't have a reproduction steps unfortunately, but I am runing into such issue on our CI in combination with the [Gitlab executor](https://github.com/cirruslabs/gitlab-tart-executor). I am not sure if it is issue for Tart or Gitlab executor, but my scenario is that the CI machine is running for weeks, everything works fine until the issue will VM limit occurs, at first occasionally, then basically all concurrent jobs fail with this error:

```
Preparing the "custom" executor
01:01
Using Custom executor...
2023/12/13 14:20:21 Pulling the latest version of <image>...
2023/12/13 14:20:22 Cloning and configuring a new VM...
2023/12/13 14:20:22 Waiting for the VM to boot and be SSH-able...
Error Domain=VZErrorDomain Code=6 "The maximum supported number of active virtual machines has been reached." UserInfo={NSLocalizedFailure=The number of virtual machines exceeds the limit., NSLocalizedFailureReason=The maximum supported number of active virtual machines has been reached.}
2023/12/13 14:21:22 tart command returned non-zero exit code: "no IP address found, is your VM running?"
ERROR: Job failed: exit status 1
```

This would by my Gitlab runner config
```
~ % cat .gitlab-runner/config.toml
concurrent = 2
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "<name>"
  url = "<url>"
  id = <id>
  token = "<token>"
  token_obtained_at = <date>
  token_expires_at = <date>
  executor = "custom"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.feature_flags]
    FF_RESOLVE_FULL_TLS_CHAIN = false
  [runners.custom]
    config_exec = "gitlab-tart-executor"
    config_args = ["config", "--cache-dir", "<cachedir>"]
    prepare_exec = "gitlab-tart-executor"
    prepare_args = ["prepare", "--concurrency", "2", "--cpu", "auto", "--memory", "auto", "--dir", "mint:<mintdir>", "--dir", "TuistCache:<tuistdir>"]
    run_exec = "gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "gitlab-tart-executor"
    cleanup_args = ["cleanup"]
```

If this issue occurs it gets fixed (or more like workarounded/postponed) by device restart - I think this might indicate that something is not cleaned up when the ephemeral job VM is disposed, but definitely no idea if this points to Tart, the Gitlab executor or the Virtualization framework.

Currently our CI machine is running macOS 14.0, the VMs also.

Last time the issue occurred we had: 
Gitlab runner 16.4.1, 
Gitlab Tart Executor 1.4 (I think 1.4.1), 
Tart 2.1.0

I tried to fix that yesterday by updating everything to the latest versions:
```
~ % brew list --versions
gitlab-runner 16.6.1
gitlab-tart-executor 1.5.0
softnet 0.7.2
tart 2.4.2
```

That did not fix the problem, but we'll see if that eventually prevents it from happening again. If not I will try to investigate a bit more, but it is quite tricky as we at least currently have a single CI machine.

**Comment by edigaryev** [comment] 2023-12-14 12:57
@olejnjak you could try running `tart list` on that host next time this happens to see which VMs are still running and also check the [Activity Monitor](https://support.apple.com/en-am/guide/activity-monitor/welcome/mac) for `tart` and `Virtualization` processes.

This should help in diagnosing the root cause.

**Comment by olejnjak** [comment] 2024-03-01 09:13
For me this seems to be issue with gitlab-runner...we have a single executor with concurrency set to 2 in config toml and I see running three jobs at the same time...

**Comment by mnm364** [comment] 2026-03-20 18:46
Sorry to revive an old thread but this is happening to me as well. Here are my reproduction steps:

```
$ tart clone ghcr.io/cirruslabs/macos-tahoe-vanilla:26.2 my-tahoe
$ tart run my-tahoe
<<<Within guest: Apple Menu -> Shut Down>>>
guest has stopped the virtual machine
$ tart list
Source Name        Disk Size Accessed       State
local  my-tahoe    50   25   3 minutes ago  stopped
$ tart run my-tahoe
<<<Within guest: Apple Menu -> Shut Down>>>
guest has stopped the virtual machine
$ tart list
Source Name        Disk Size Accessed       State
local  my-tahoe    50   25   45 seconds ago stopped
$ tart run my-tahoe
The number of VMs exceeds the system limit
```

I have also tried variants of using `tart stop my-tahoe` to stop the VMs from the host as well as running `sudo shutdown -h now` from the guest in lieu of clicking through to shutdown through the macOS menus. Both bring me back to the same broken state.

Here is my host system configuration:
```
$ tart --version
2.31.0
```
```
$ sw_vers
ProductName:		macOS
ProductVersion:		26.3.1
BuildVersion:		25D2128
```

To get out of this state I need to restart my host macOS machine, which basically makes this unusable for me. Any help appreciated. Thanks!
