### ISSUE TITLE
`tart ip` returns invalid IP when running a Linux VM with `--net-bridged`

### ISSUE THREAD

**Issue by apachont** [cirruslabs/tart#460] opened 2023-03-31 17:35 UTC
Running VMs with the "net-bridged" adapter is excellent, but the `tart ip`  still prints the NAT address of the VM:
```
% tart run --rosetta rosetta --net-bridged en0 myvm-1234 
% tart ip myvm-1234
192.168.64.6
```
Using `--resolver arp` returns `no IP address found`:
```
% tart ip --resolver arp myvm-1234
no IP address found, is your VM running?
% tart ip --resolver=arp myvm-1234
no IP address found, is your VM running?
```

This issue is important because the packer plugin uses the same command ([here](https://github.com/cirruslabs/packer-plugin-tart/blob/main/builder/tart/ssh.go#L9)) to retrieve the IP address and initiate an SSH session while the builder creates artefacts. 
Regards

**Comment by fkorotkov** [comment] 2023-03-31 17:55
@apachont could you please share output of `arp -an` and `cat ~/.tart/vms/myvm-1234/config.json`. Also how do you create `myvm-1234` VM? Cloning from a local VM, creating from scratch or pulling a remote one?

**Comment by apachont** [comment] 2023-04-03 10:54
@fkorotkov, here you go:
`cat ~/.tart/vms/myvm-1234/config.json`:
```
{
  "memorySize" : 17179869184,
  "arch" : "arm64",
  "os" : "linux",
  "cpuCountMin" : 4,
  "display" : {
    "width" : 1024,
    "height" : 768
  },
  "cpuCount" : 4,
  "version" : 1,
  "macAddress" : "7e:1c:f2:4a:78:30",
  "memorySizeMin" : 4294967296
}%
```

`arp -an`:
```
~ % arp -an
? (192.168.1.1) at 60:8d:26:ef:6d:cd on en0 ifscope [ethernet]
? (192.168.1.13) at ec:c4:d:76:c6:32 on en0 ifscope [ethernet]
? (192.168.1.17) at e6:e8:c3:76:d9:c8 on en0 ifscope [ethernet]
? (224.0.0.251) at 1:0:5e:0:0:fb on en0 ifscope permanent [ethernet]
? (230.230.230.230) at 1:0:5e:66:e6:e6 on en0 ifscope permanent [ethernet]
```

The VM was cloned from a "base" VM. The "base" image uses the default NAT interface adapter.

**Comment by edigaryev** [comment] 2023-04-03 11:06
Hello Andres! 👋

Does `myvm-1234` actually gets any IP address from the network (if you go to `Settings → Network → Ethernet → Details` inside of the VM)?

Does your network on `en0` has a DHCP server that is offering IP addresses for computers with `7e:1c:f2:4a:78:30` MAC address?

**Comment by edigaryev** [comment] 2023-04-03 14:09
I've just realized that I might've closed this too early.

@apachont, can you clarify that the root cause for the issue you're facing is found?

**Comment by apachont** [comment] 2023-04-03 18:00
@edigaryev I understand the root cause is the IP not included in the output of the arp command; however, the `tart ip` command should provide the correct IP address, which is not. As described in the initial comment, the packer plugin for Tart use `tart ip` to retrieve the IP address of the VM and establish SSH communication. 

 It might be worth it to investigate if there is room for improvement.

**Comment by fkorotkov** [comment] 2023-04-05 15:09
@apachont which Linux distribution you are trying with? I tried with Ubuntu Desktop and `tart ip --resolver arp` worked. @edigaryev tried with Ubuntu Server and it didn't work.

<img width="1324" alt="Screenshot 2023-04-05 at 10 44 12 AM" src="https://user-images.githubusercontent.com/989066/230124087-47add853-08a4-45d8-bb0a-f8ca3d5421b2.png">

**Comment by apachont** [comment] 2023-04-05 15:47
I reach the same point you expose, so please let me share additional context. I'm deploying a local environment that requires multiple VMs to communicate with each other, which is impossible due to isolation from the NAT interface itself. 

@fkorotkov I'm using the Ubuntu server.  I'm not a big fan of setting up Linux desktop VMs for server tasks, but Packer can add the `net.ipv4.icmp_echo_ignore_broadcasts` parameter to the `sysctl.conf` making the VM discoverable from arp.

Thank you both for investigating the issue.

**Closed** 2023-04-05 18:19 UTC
Labels: not possible atm

**Comment by fkorotkov** [comment] 2023-04-05 19:35
Since it's a caveat for some Linux distributions. I've made the error message cleaner in #464.
